### ISSUE TITLE
python manage.py runserver 报错

### ISSUE THREAD

**Issue by hanbing** [small99/AutoLine#5]
运行命令 python manage.py runserver -h 0.0.0.0 -p 8000 ， 无法执行。

错误信息如下：
Import environment from .env
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/apscheduler/schedulers/base.py", line 882, in _create_plugin_instance
    plugin_cls = class_container[alias]
KeyError: 'sqlalchemy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 76, in <module>
    app.config["TRIGGER"].setup()
  File "/home/ubuntu/AutoLine-master/app/utils/trigger.py", line 43, in setup
    'apscheduler.timezone': 'UTC',
  File "/usr/local/lib/python3.5/dist-packages/apscheduler/schedulers/base.py", line 83, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/lib/python3.5/dist-packages/apscheduler/schedulers/base.py", line 122, in configure
    self._configure(config)
  File "/usr/local/lib/python3.5/dist-packages/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/lib/python3.5/dist-packages/apscheduler/schedulers/base.py", line 735, in _configure
    jobstore = self._create_plugin_instance('jobstore', plugin, value)
  File "/usr/local/lib/python3.5/dist-packages/apscheduler/schedulers/base.py", line 885, in _create_plugin_instance
    plugin_cls = class_container[alias] = plugin_container[alias].load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 808, in resolve
    if not req_extras.markers_pass(req):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 993, in markers_pass
    return not req.marker or any(extra_evals) or req.marker.evaluate()
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/markers.py", line 278, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/markers.py", line 203, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/markers.py", line 185, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
pkg_resources.extern.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.

**Comment by small99** [comment]
1. 请确保是最新的代码
2. 安装所有的依赖pip install -r requirements.txt
3. 还有问题请注明os版本、python版本以及mysql版本以及截图、日志等信息

**Comment by andy1980** [comment]
倒腾了一天，终于跑起来了。
